<?php

if (PHP_SAPI !== 'cli') {
    fwrite(STDERR, "This generator must be run from CLI.\n");
    exit(1);
}

$root = dirname(__DIR__, 2);
$dictionary_path = $root . '/core/infrastructure/master-data/system-dictionary.json';
$php_out = $root . '/core/contracts/ReasonCodes.php';
$js_out = $root . '/core/contracts/ReasonCodes.js';

if (!file_exists($dictionary_path)) {
    fwrite(STDERR, "Missing dictionary file: {$dictionary_path}\n");
    exit(1);
}

$raw = file_get_contents($dictionary_path);
$raw = (string) $raw;
if (substr($raw, 0, 3) === "\xEF\xBB\xBF") {
    $raw = substr($raw, 3);
}
$decoded = json_decode((string) $raw, true);
if (!is_array($decoded) || !isset($decoded['reasonCodes']) || !is_array($decoded['reasonCodes'])) {
    fwrite(STDERR, "Invalid system-dictionary.json: reasonCodes object is required.\n");
    exit(1);
}

$reason_codes = array();
foreach ($decoded['reasonCodes'] as $code => $meta) {
    $normalized = strtoupper(trim((string) $code));
    if ($normalized === '') {
        continue;
    }
    $reason_codes[] = $normalized;
}
$reason_codes = array_values(array_unique($reason_codes));
if (empty($reason_codes)) {
    fwrite(STDERR, "No reason codes found in dictionary.\n");
    exit(1);
}

$php_lines = array();
$php_lines[] = '<?php';
$php_lines[] = '';
$php_lines[] = '// Auto-generated by core/contracts/generate-reason-codes.php. Do not edit manually.';
$php_lines[] = '';
$php_lines[] = "if (!class_exists('TopInstal_ReasonCodes')) {";
$php_lines[] = '    class TopInstal_ReasonCodes {';
foreach ($reason_codes as $code) {
    $php_lines[] = "        const {$code} = '{$code}';";
}
$php_lines[] = '    }';
$php_lines[] = '}';
$php_lines[] = '';

$js_lines = array();
$js_lines[] = '// Auto-generated by core/contracts/generate-reason-codes.php. Do not edit manually.';
$js_lines[] = "const ReasonCodes = Object.freeze({";
foreach ($reason_codes as $code) {
    $js_lines[] = "  {$code}: '{$code}',";
}
$js_lines[] = '});';
$js_lines[] = '';
$js_lines[] = "if (typeof module !== 'undefined' && module.exports) {";
$js_lines[] = '  module.exports = ReasonCodes;';
$js_lines[] = '}';
$js_lines[] = '';

$php_payload = implode(PHP_EOL, $php_lines);
$js_payload = implode(PHP_EOL, $js_lines);

file_put_contents($php_out, $php_payload);
file_put_contents($js_out, $js_payload);

fwrite(STDOUT, "Generated ReasonCodes from {$dictionary_path}\n");
