const DocumentReasonCodes = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  NONCE_INVALID: 'NONCE_INVALID',
  AGENT_KEY_INVALID: 'AGENT_KEY_INVALID',
  RATE_LIMITED: 'RATE_LIMITED',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
  KIT_NOT_FOUND: 'KIT_NOT_FOUND',
  DOCX_RENDER_FAILED: 'DOCX_RENDER_FAILED',
  PDF_CONVERTER_UNAVAILABLE: 'PDF_CONVERTER_UNAVAILABLE',
  PDF_CONVERSION_FAILED: 'PDF_CONVERSION_FAILED',
  STORAGE_ERROR: 'STORAGE_ERROR',
  UNSUPPORTED_MODE: 'UNSUPPORTED_MODE',
  UNSUPPORTED_DOCUMENT_TYPE: 'UNSUPPORTED_DOCUMENT_TYPE',
  UNSUPPORTED_OUTPUT_FORMAT: 'UNSUPPORTED_OUTPUT_FORMAT',
  MAPPED_FROM_OFFER_DTO: 'MAPPED_FROM_OFFER_DTO',
  FALLBACK_DOCX_RETURNED: 'FALLBACK_DOCX_RETURNED',
});

if (typeof module !== 'undefined' && module.exports) {
  module.exports = DocumentReasonCodes;
}

