<?php

if (!class_exists('TopInstal_DocumentReasonCodes')) {
    class TopInstal_DocumentReasonCodes {
        const VALIDATION_ERROR = 'VALIDATION_ERROR';
        const AUTH_REQUIRED = 'AUTH_REQUIRED';
        const NONCE_INVALID = 'NONCE_INVALID';
        const AGENT_KEY_INVALID = 'AGENT_KEY_INVALID';
        const RATE_LIMITED = 'RATE_LIMITED';
        const TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND';
        const KIT_NOT_FOUND = 'KIT_NOT_FOUND';
        const DOCX_RENDER_FAILED = 'DOCX_RENDER_FAILED';
        const PDF_CONVERTER_UNAVAILABLE = 'PDF_CONVERTER_UNAVAILABLE';
        const PDF_CONVERSION_FAILED = 'PDF_CONVERSION_FAILED';
        const STORAGE_ERROR = 'STORAGE_ERROR';
        const UNSUPPORTED_MODE = 'UNSUPPORTED_MODE';
        const UNSUPPORTED_DOCUMENT_TYPE = 'UNSUPPORTED_DOCUMENT_TYPE';
        const UNSUPPORTED_OUTPUT_FORMAT = 'UNSUPPORTED_OUTPUT_FORMAT';
        const MAPPED_FROM_OFFER_DTO = 'MAPPED_FROM_OFFER_DTO';
        const FALLBACK_DOCX_RETURNED = 'FALLBACK_DOCX_RETURNED';
    }
}

